### ISSUE TITLE
Create code comment idenifier for copyright holders 

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#122] opened 2019-05-14 17:34 UTC
FSF via @kestewart  requested if we could come up with a identifier for the copyrightholders in a code file similar to `SPDX-License-Identifier: Apache-2.0`

**Comment by tsteenbe** [comment] 2019-05-14 17:35
@kestewart  Feel free to update edit above ticket to properly capture the discussion with FSFE

**Comment by tsteenbe** [comment] 2019-05-14 17:37
@swinslow  Should be greppable - idea multiple statement for each copyright holder
```
SPDX-Copyright-Identifier: Linux Foundation 2011 - 2019
SPDX-Copyright-Identifier: Redhat Inc. 2013 - 2016
```

**Comment by goneall** [comment] 2019-05-14 18:06
Handling multiple lines would be one of the considerations.

**Comment by goneall** [comment] 2019-05-14 18:08
Propose - `SPDX-Copyright-Text:` to match the spec term `CopyrightText`

**Comment by swinslow** [comment] 2019-05-14 18:26
I'd suggest just `SPDX-Copyright` -- want to keep it simple to minimize barriers so people use it.

* `-Identifier` made sense in the license context, but there isn't really an equivalent here
* `-Text` does match the spec but I'm not sure if it adds much beyond just `SPDX-Copyright`?

The comment from @tsteenbe above raises another good point: what should the content of the text field be, after the tag itself? 

Looking at how some individuals and companies list their copyright lines, they often want to include the word "Copyright" in the notice text itself; and/or the (C) symbol (in parentheses and/or a literal "C in a circle" symbol); etc. 

I think we should take one of the following approaches:
1. either we take no opinion on what _should_ go after the tag, and treat it as free-form text; or
2. if not that, then the legal team may want to review and weigh in if any recommendation is made as to what should go there.

**Comment by zvr** [comment] 2019-05-14 19:38
If we'll go to all the trouble of defining something new and potentially create such lines (like we do with `SPDX-License-Identifier` ones), it would be a great shame to leave the content completely unstructured.

Of course, existing copyright notices *are* unstructured, some have companies or people names, some include emails while others not, etc. I don't think we care about breaking down any of this info in more detail. But we *do* care about the time (years) that are usually present.

Therefore I propose:
`SPDX-Copyright: `, whatever years are mentioned, `;` , whatever else is mentioned.
For example:

    SPDX-Copyright: 2011-2015,2019 ; Some company or person <maybe@an.email>

**Comment by swinslow** [comment] 2019-05-14 20:46
As much as I love structure (and I do)  :)  -- my concern is this:

In conversations with various folks regarding copyright notice formats, I've seen that some have strong opinions about what is necessary vs. desirable vs. unnecessary. In some cases this is personal preference. In others it's a matter of interpretation of statutes which vary by jurisdiction, and which some see as mandatory while others don't.

I think that any attempt for us to recommend a particular format _for the copyright text itself_ is going to be (1) controversial and (2) detract from the key goal. 

In my mind (and feel free to disagree!) the key goal here is to get source code copyright notices, _whatever they say_, into a standardized and machine-readable location so that they can be easily detected (via `grep` or otherwise) and reproduced for license compliance purposes. As far as SPDX is concerned, I'm more interested in making it easier to capture and reproduce the applicable compliance-related content, whatever it says, rather than dipping into something that feels more "legal recommendation"-y.

**Comment by goneall** [comment] 2019-05-20 15:43
There is a related PR in the FSFE/Reuse spec: https://github.com/fsfe/reuse-docs/pull/23 

Note - the reuse docs use the CC-BY-SA license

**Comment by carmenbianca** [comment] 2019-05-20 16:33
> I propose:
> `SPDX-Copyright: `, whatever years are mentioned, `;` , whatever else is mentioned.

I would like to agree with this, but I can see this being potentially harmful. For instance, you get a hold of a piece of code that does not conform to this structure, then what do you do? Maybe you change the order around a bit, but what if the code is from Microsoft and the year isn't mentioned at all?

In the draft of the REUSE spec we strongly recommend something along the lines of `SPDX-Copyright: [year(s)] [copyright holder] <[contact address]>`. This is obviously subject to change, and the spec will not be published until there is consensus within SPDX.

**Comment by mxmehl** [comment] 2019-05-24 10:43
To add a concrete use case: 

Imagine a properly licensed file without SPDX-Copyright containing some text about Copyright, e.g. as output for a `--help` flag, or even something completely unrelated to the actual license of the file. How should compliance tools handle this situation, if they find multiple occasions of `Copyright`, `©` or `(c)`, which may also match some pattern with years behind them?

As @swinslow mentioned, `SPDX-Copyright` would make scraping the *actual* license information more resistant and less dependent on  complex patterns. Making it mandatory immediately would break SPDX compliance of many projects, but making it a strong recommendation could help move existing and new projects in a better direction.

**Comment by silverhook** [comment] 2019-05-27 12:22
>     1. either we take no opinion on what _should_ go after the tag, and treat it as free-form text; or

From practical PoV, I would go for this on SPDX level and let (other) best practices (e.g. REUSE) handle what should go there.

>     2. if not that, then the legal team may want to review and weigh in if any recommendation is made as to what should go there.

See https://github.com/fsfe/reuse-docs/issues/5 for some prior discussion on this.

**Comment by swinslow** [comment] 2019-07-10 16:54
I'll plan to bring this up for discussion on the SPDX Legal Team call tomorrow.

**Comment by jeremiah** [comment] 2019-07-10 17:53
I think that 'SPDX-Copyright' is ambiguous and unnecessary. 

- Is the SPDX-Copyright line going to be per-file? What happens if someone uses the SPDX-Copyright as the copyright for the entire work when the copyright has multiple holders in different parts of the whole work? (This is a common case.)
- If existing copyright notices are going to be extant will they continue to be considered authoritative? And if so, what purpose does the SPDX-Copyright tag serve? 
- SPDX-Copyright tag will be redundant and lead to legal confusion as to what is under, and who's assigned, copyright.

**Comment by swinslow** [comment] 2019-07-10 18:32
In my view, the use of an `SPDX-Copyright` tag would have one, and only one, purpose: to make it easier to automatically `grep` and extract copyright statements in code. So that they can be incorporated into attribution notices, or SPDX bill-of-materials documents, or however else one wants to use them.

I see problems with scanners trying to identify copyright statements, where they may e.g. pick up the word "copyright" in incorrect contexts such as part of the actual license text, or where used in other ways than to designate a copyright notice. If contributors prefix a notice instead with `SPDX-Copyright:`, we can grep for that. That's the only advantage I see.

For SPDX purposes, that's also why I'm pretty strongly against SPDX saying the copyright notice should be formatted in any particular way. I think that's perhaps fully appropriate for REUSE to recommend an approach. But for SPDX itself, I really see this just as a way to make it easier to identify where the copyright notices are located in sources.

> Is the SPDX-Copyright line going to be per-file? What happens if someone uses the SPDX-Copyright as the copyright for the entire work when the copyright has multiple holders in different parts of the whole work? (This is a common case.)

Fair question. But the same thing applies if there's a bare "Copyright XYZ" notice sitting in source or documentation files. Using an `SPDX-Copyright:` prefix doesn't solve that, it just makes it easier to identify and extract them, so one can interpret them as they see fit.

> If existing copyright notices are going to be extant will they continue to be considered authoritative? And if so, what purpose does the SPDX-Copyright tag serve?

It doesn't guarantee that it reports _all_ copyright notices, similar to how `SPDX-License-Identifier:` doesn't guarantee that all applicable licenses appear in the tag. It just means that if contributors do use the tag, it is easier to automate extracting the relevant text to use for attribution notices or however else is desired.

> SPDX-Copyright tag will be redundant and lead to legal confusion as to what is under, and who's assigned, copyright.

I'm not sure I follow. I guess I don't see this as being any different for how you would interpret a bare "Copyright XYZ" statement sitting in a file. I think the interpretation (and potential ambiguity) would be the same in either case.

**Comment by goneall** [comment] 2019-07-11 01:36
> I'm conformable with SPDX saying, 'hey you should identify the license in every file', but I'm not sure I'm comfortable with SPDX (essentially) saying, 'hey you should identify the copyright holder in every file' 

How about saying - 'if you include a copyright notice in a file, you should precede it with the XXX tag' (whatever the best tag name is).

If a consumer wants to identify copyrights in a file and producers want to make it easy to have the copyrights be identified, having a tag would be really useful.

Perhaps we can separate out the policy aspects of copyrights from the technical aspects of identifying the copyrights.

**Comment by mxmehl** [comment] 2019-07-11 07:57
> In my view, the use of an SPDX-Copyright tag would have one, and only one, purpose: to make it easier to automatically grep and extract copyright statements in code. So that they can be incorporated into attribution notices, or SPDX bill-of-materials documents, or however else one wants to use them.

FWIW, I agree. That is why REUSE would *recommend* using of this tag, not mandating it, see [the FAQ](https://github.com/fsfe/reuse-docs/blob/master/faq.md#do-i-use-spdx-copyright-copyright-or--copyright-symbol). Even more so, we do not strongly recommend any specific format of the copyright notice but only give a few pointers for our users.

> Perhaps we can separate out the policy aspects of copyrights from the technical aspects of identifying the copyrights.

Good point, thank you!

**Comment by jeremiah** [comment] 2019-07-11 15:38
> In my view, the use of an `SPDX-Copyright` tag would have one, and only one, purpose: to make it easier to automatically `grep` and extract copyright statements in code. 

But you already have to grep for copyright. How does putting SPDX- in front if it help?

**Comment by carmenbianca** [comment] 2019-07-11 15:47
> But you already have to grep for copyright. How does putting SPDX- in front if it help?

It greatly reduces false positives. Entertain the following comment header:

```
# This file is Copyright 2019 Jane Doe.
# The parts from project foo are copyright Joe Anybody.
# Copyright is waived for all the sections marked with "WAIVED"
```

You'd have to write fairly advanced heuristics to make sense of this file without any false positives/negatives. In contrast, this regex can quite accurately and inambiguously parse `SPDX-Copyright` lines (and discard `*/` or `-->` comment delimiters):

`(SPDX-Copyright: .*?)(?:\*/)*(?:-->)*$`

**Comment by jeremiah** [comment] 2019-07-11 15:51
> > SPDX-Copyright tag will be redundant and lead to legal confusion as to what is under, and who's assigned, copyright.
> 
> I'm not sure I follow. I guess I don't see this as being any different for how you would interpret a bare "Copyright XYZ" statement sitting in a file. I think the interpretation (and potential ambiguity) would be the same in either case.

So the only real use case for SPDX-Copyright is in code scanners for people who work with open source software. I say that because identifying licensing and copyright is a solved problem in the Free Software community, we have tools and conventions for those tools;

- https://wiki.debian.org/CopyrightReviewTools
- https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

From what I understand the SPDX 'short tags' come from Debian as well. The point is, that SPDX is a spec that has a very specific audience that frankly doesn't understand FOSS licensing. They have a single mission; preserve plausible deniability via due diligence in a risk averse for-profit enterprise. Code scanning tools have found a powerful niche and take advantage of information asymmetry. But code scanning tool profit is detrimental to the Free Software movement because it relies on the fear, uncertainty, and doubt spread for years regarding FOSS licensing. 

It is far, far better for groups like the Linux Foundation and Reuse org to educate people on the use of copyleft and other FOSS licensing than it is to sell them fancy tooling. Yes, the profits are not as high, but it significantly benefits end users, FOSS licenses, and the ecosystem in general.

**Comment by jeremiah** [comment] 2019-07-11 15:56
> > But you already have to grep for copyright. How does putting SPDX- in front if it help?
> 
> It greatly reduces false positives. 

Reduce, but not eliminate. You'll never reduce false positives to the point where you don't need human intervention. And the reduction of false positives may lead to a similar reduction in positive identification where actual third-party copyright is ignored.

Entertain the following comment header:
> 
> ```
> # This file is Copyright 2019 Jane Doe.
> # The parts from project foo are copyright Joe Anybody.
> # Copyright is waived for all the sections marked with "WAIVED"
> ```
> 
> You'd have to write fairly advanced heuristics to make sense of this file without any false positives/negatives. In contrast, this regex can quite accurately and inambiguously parse `SPDX-Copyright` lines (and discard `*/` or `-->` comment delimiters):
> 
> `(SPDX-Copyright: .*?)(?:\*/)*(?:-->)*$`

My strong recommendation is that you wouldn't write heuristics to make sense of that file. That file needs to be made sense of by a human.

**Comment by carmenbianca** [comment] 2019-07-11 16:19
> I say that because identifying licensing and copyright is a solved problem in the Free Software community

I'm not certain that this is true. The Free Software community is bigger than Debian. I encounter _a lot_ of individual files that do not succinctly describe their copyright and licensing information in the header. You'll often find:

- No header at all.
- Only copyright in the header.
- Only the license in the header.

And almost *never* in a format that is easily parsed. That's what you linked all those tools: Because heuristics and manual labour is the only way to make sense of all the variant comment headers. So I think that this:

> It is far, far better for groups like the Linux Foundation and Reuse org to educate people on the use of copyleft and other FOSS licensing than it is to sell them fancy tooling

is an inaccurate characterisation, because at REUSE we're trying to do the exact opposite: Introduce a standard for declaring copyright and licensing that is unambiguously parseable by primitive tools.

Of course, once you have introduced such a standard, writing *advanced tools* becomes a lot easier as a side effect.

> My strong recommendation is that you wouldn't write heuristics to make sense of that file. That file needs to be made sense of by a human.

Granted, but not the point I was trying to make. I was trying to demonstrate that it is difficult to grep. Alternatively, entertain this file:

```
# This file is Copyright 2017 Jane Doe
# Later revisions are copyright Joe Anybody

This file is all about copyright. Copyright is a legal thingamabob that grants authors
certain rights. Authors often declare copyright with a copyright notice such as
"Copyright © 2019 The Author".

Blah blah blah blah copyright
```

If `SPDX-Copyright` were used instead in such a file, it'd be really easy to grep. I'm not suggesting that any of these are perfect examples, but I'm saying that `SPDX-Copyright` solves a problem of unambiguously communicating copyright notices that can reduce a lot of manual labour.

> Reduce, but not eliminate. You'll never reduce false positives to the point where you don't need human intervention. And the reduction of false positives may lead to a similar reduction in positive identification where actual third-party copyright is ignored.

I don't think perfect should be the enemy of good. And I am not certain how third-party copyright would be ignored.

> The point is, that SPDX is a spec that has a very specific audience that frankly doesn't understand FOSS licensing. They have a single mission; preserve plausible deniability via due diligence in a risk averse for-profit enterprise. Code scanning tools have found a powerful niche and take advantage of information asymmetry. But code scanning tool profit is detrimental to the Free Software movement because it relies on the fear, uncertainty, and doubt spread for years regarding FOSS licensing.

I want to ask you to please preserve a nice and kind environment. I don't think that it is productive to attribute malice to people who are trying to improve Free Software in their own way.

**Comment by jeremiah** [comment] 2019-07-11 17:20
So here's why SPDX-Copyright is ambiguous IMHO;

1. What does it refer to? Does it refer to the SPDX copyright? The copyright of the file? Or the copyright of the work as a whole?
2. If the SPDX-Copyright field is populated with a copyright assignment, is that now or will it become the valid copyright? What if the SPDX-Copyright field is incorrect or incomplete yet is taken to be authoritative? 

As @jlovejoy says " I'm conformable with SPDX saying, 'hey you should identify the license in every file', but I'm not sure I'm comfortable with SPDX (essentially) saying, 'hey you should identify the copyright holder in every file' especially when not every license (including some of the most widely used licenses) do not require the reproduction of copyright notices for a binary distribution (which, I believe, is where this can become a PITA)"

I think that if you want something to ease the use of copyrighted material, use a reliable tool to find the string "[C|c]opyright". This is going to produce the best results and trying to force a structured data approach is a Bad Idea :tm:.  If you really want machines to do this, perhaps use Machine Learning and then compare the results to human understanding.

**Comment by goneall** [comment] 2019-07-11 18:09
I would start with the [SPDX file copyright text definition](https://github.com/spdx/spdx-spec/blob/master/chapters/4-file-information.md#48-copyright-text-).    My assumption is that we would use the same definition for the inline code copyright references.  Let me know if anyone is making a different assumption.

If this definition is ambiguous, we should create an issue (or better yet, a pull request to clarify).  

Note: there is a distinct but very related field [File Notice](https://github.com/spdx/spdx-spec/blob/master/chapters/4-file-information.md#413-file-notice-).   If the intent is to identify the file notices in source files, we could create another tag like `SPDX-FileNotice:`.

**Comment by carmenbianca** [comment] 2019-07-11 19:13
> I would start with the [SPDX file copyright text definition](https://github.com/spdx/spdx-spec/blob/master/chapters/4-file-information.md#48-copyright-text-). My assumption is that we would use the same definition for the inline code copyright references. Let me know if anyone is making a different assumption.

This is correct. The proposed `SPDX-Copyright` tag maps exactly onto SPDX File Copyright Text, just like the `SPDX-License-Identifier` tag maps exactly onto SPDX File License Information in File.

**Comment by mxmehl** [comment] 2019-07-15 10:21
> I'll plan to bring this up for discussion on the SPDX Legal Team call tomorrow.

@swinslow Have you been successful? If so, could you please share some results?

**Comment by jlovejoy** [comment] 2019-07-18 03:59
@mxmehl  - we had a really good discussion and fleshed out some of the concerns posted here (or that I posted here ;) 
just posted meeting minutes here: https://wiki.spdx.org/view/Legal_Team/Minutes/2019-07-11
Key takeaway (and hopefully others on call agree): was the importance of mapping on existing fields in the spec, as there have been similar questions to use spec fields in other places (than an SPDX doc) and so if we are consistent it paves a way for use of other fields, if people so desire.

**Comment by jlovejoy** [comment] 2019-07-18 04:04
other key point I meant to mention: key factor in ensuring this is done right is how the appendix explaining it is drafted. I think I had some succinct summary during the legal call, but it didn't get recorded and I'm at a loss now... hopefully it will come back to me later!

**Comment by mxmehl** [comment] 2019-07-23 10:17
Thanks for sharing the minutes. I see no collision with what REUSE intends for this tag, and I appreciate that the SPDX spec wants to take care of possible misunderstandings here (e.g. left vs. right side).

However, since we will release the REUSE spec 3.0 soon, it would be helpful to have an estimation whether we would be on the safe side to introduce SPDX-Copyright already. According to the minutes, there has been some debate about its name (FileCopyrightText?) for example. What do you think?

**Comment by swinslow** [comment] 2019-07-23 13:32
Thanks @mxmehl. Based on the minutes and conversation it is not yet locked down, particularly since any explanatory appendix has yet to be drafted, but just speaking for myself:

I think it is more likely that the tag recommended by SPDX would be `SPDX-FileCopyrightText:` as that mirrors the SPDX spec fields. I do not expect that SPDX would recommend or encourage use of `SPDX-Copyright:` as the tag.

**Comment by zvr** [comment] 2019-07-23 16:18
I think the general consensus in both the legal and tech team call was that the general rule for adding SPDX information inside files would be to use the form `SPDX-tagname:` where *tagname* is one of the tags defined in the SPDX spec for tag-value format.
Therefore, as @swinslow writes, this convention results in `SPDX-FileCopyrightText:`.

[yes, we understand that the already existing `SPDX-License-Identifier` does not match this rule, but we cannot  change the past...]

**Comment by silverhook** [comment] 2019-07-23 16:36
`SPDX-FileCopyrightText:` sounds like more than an acceptable solution to me.

Especially if with this REUSE can be used as a use case on how to write SPDX tags in files.

**Comment by mxmehl** [comment] 2019-07-24 08:13
Thanks for sharing your opinions everyone! As REUSE, we will have to think about this. The worst case would be that we start recommending a specific format which is not accepted by SPDX and other license compliance projects down the road.

From my personal perspective, `SPDX-FileCopyrightText` is less intuitive for developers than `SPDX-Copyright`, but the argument of being consistent with the convention is logical from the SPDX perspective.

**Comment by jlovejoy** [comment] 2019-07-25 16:34
@mxmehl - looks like your time frame for feedback on the next REUSE release is closing soon and we have yet to even start drafting the appendix needed for this. 

Ideally we'd have the appendix in a merged PR, even if a new version of the spec has not yet been released, before you recommend this in REUSE. Would it be possible for you to continue with your release, and just leave this section out and then add it later?

We could also use some help with the drafting... happy to have help there, if you want to contribute to that timeline :)

@goneall @kestewart - has anyone been tasked on the tech team calls with starting this?

**Comment by kestewart** [comment] 2020-02-03 13:56
https://github.com/spdx/spdx-spec/pull/193 fixes this issue.

**Closed** 2020-02-11 18:14 UTC
Labels: legal team review
