### ISSUE TITLE
Add License Matching Guidelines from Web into Appendix II of specification

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#43] opened 2017-10-12 17:42 UTC
[](https://spdx.org/spdx-license-list/matching-guidelines) should be tracked in the spec in Appendix 2.

Also,  we should review also [](https://spdx.org/spdx-license-list/license-list-overview) to move redundancy into the Appendix. 

Discussed on Legal Call on 2017/10/12.

**Comment by wking** [comment] 2017-10-12 18:01
Duplicate of #32?

**Comment by iamwillbar** [comment] 2020-01-22 20:01
Yes, this appears to be a duplicate of #32. Closing, re-open if it's not a duplicate.

**Closed by iamwillbar** 2020-01-22 20:01 UTC
Labels: enhancement
